columns = [
	{"fieldname":"name","fieldtype":"Link","options":"Customer","label":"Customer"},
	{"fieldname":"customer_name","fieldtype":"Data","options":"","label":"Customer Name"},
	{"fieldname":"customer_group","fieldtype":"Link","options":"Customer Group", "label":"Customer Group"},
	{"fieldname":"account","fieldtype":"Link","options":"Account", "label":"Account"},
	{"fieldname":"address_title","fieldtype":"Data","options":"","label":"Address Title"},
	{"fieldname":"address_type","fieldtype":"Select","options":"Billing\nShipping\nOffice\nPersonal\nPlant\nPostal\nShop\nSubsidiary\nWarehouse\nCurrent\nPermanent\nOther","label":"Address Type"},
	{"fieldname":"address_line1","fieldtype":"Data","options":"","label":"Address Line 1"},
	{"fieldname":"address_line2","fieldtype":"Data","options":"","label":"Address Line 2"},
	{"fieldname":"city","fieldtype":"Data","options":"","label":"City/Town"},
	{"fieldname":"county","fieldtype":"Data","options":"","label":"County"},
	{"fieldname":"state","fieldtype":"Data","options":"","label":"State"},
	{"fieldname":"country","fieldtype":"Link","options":"Country","label":"Country"},
	{"fieldname":"pincode","fieldtype":"Data","options":"","label":"Postal Code"},
	{"fieldname":"email_id","fieldtype":"Data","options":"Email","label":"Email Address"},
	{"fieldname":"phone","fieldtype":"Data","options":"","label":"Mobile No"},
	{"fieldname":"fax","fieldtype":"Data","options":"","label":"Fax"},
	{"fieldname":"is_primary_address","fieldtype":"Check","options":"","label":"Preferred Billing Address"},
	{"fieldname":"is_shipping_address","fieldtype":"Check","options":"","label":"Preferred Shipping Address"},
]